
variable "aws_access_key" {
  type    = string
  default = "AKIA4IKFXY6NOHQTPD6I"
}

variable "aws_secret_key" {
  type    = string
  default = "8rCIfCcRpvQKRmAuYOG94BvaM9M9yiqBvLD7FF0L"
}

variable "destination_regions" {
  type    = string
  default = "us-west-1,us-west-2,us-east-1,us-east-2"
}

data "amazon-ami" "autogenerated_1" {
  access_key = "${var.aws_access_key}"
  filters = {
    name                = "ubuntu/images/*ubuntu-xenial-16.04-amd64-server-*"
    root-device-type    = "ebs"
    virtualization-type = "hvm"
  }
  most_recent = true
  owners      = ["099720109477"]
  region      = "us-west-1"
  secret_key  = "${var.aws_secret_key}"
}

source "amazon-ebs" "autogenerated_1" {
  access_key            = "${var.aws_access_key}"
  ami_name              = "packer-vanilla-t2.micro"
  ami_regions           = "${var.destination_regions}"
  force_delete_snapshot = "true"
  force_deregister      = "true"
  instance_type         = "t2.micro"
  region                = "us-west-1"
  secret_key            = "${var.aws_secret_key}"
  source_ami            = "${data.amazon-ami.autogenerated_1.id}"
  ssh_username          = "ubuntu"
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

}
