
# could not parse template for following block: "template: hcl2_upgrade:4: function \"AKIA4IKFXY6NOHQTPD6I\" not defined"

variable "AWS_ACCESS_KEY" {
  type    = string
  default = "AKIA4IKFXY6NOHQTPD6I"
}
/*
variable "AWS_GITHUB_TOKEN" {
  type    = string
  default = "${env("AWS_GITHUB_TOKEN")}"
}*/

# could not parse template for following block: "template: hcl2_upgrade:4: bad number syntax: \"8r\""

variable "AWS_SECRET_KEY" {
  type    = string
  default = "8rCIfCcRpvQKRmAuYOG94BvaM9M9yiqBvLD7FF0L"
}

variable "DESTINATION_REGIONS" {
  type    = string
  default = "us-west-1"
}

data "amazon-ami" "autogenerated_1" {
  access_key = "${var.AWS_ACCESS_KEY}"
  filters = {
    name                = "ubuntu/images/*ubuntu-xenial-16.04-amd64-server-*"
    root-device-type    = "ebs"
    virtualization-type = "hvm"
  }
  most_recent = true
  owners      = ["099720109477"]
  region      = "us-west-1"
  secret_key  = "${var.AWS_SECRET_KEY}"
}

source "amazon-ebs" "autogenerated_1" {
  access_key            = "${var.AWS_ACCESS_KEY}"
  ami_name              = "packer-vanilla-t2.micro"
  ami_regions           = "${var.DESTINATION_REGIONS}"
  force_delete_snapshot = "true"
  force_deregister      = "true"
  instance_type         = "t2.micro"
  region                = "us-west-1"
  secret_key            = "${var.AWS_SECRET_KEY}"
  source_ami            = "${data.amazon-ami.autogenerated_1.id}"
  ssh_username          = "ubuntu"
  //user_data_file        = "/github/workspace/scripts/ami_user_data.sh"
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]
/*
  provisioner "file" {
    destination = "/home/ubuntu/ami_user_data.sh"
    source      = "/github/workspace/scripts/ami_user_data.sh"
  }

  provisioner "shell" {
    inline = ["echo '${var.AWS_GITHUB_TOKEN}' > /home/ubuntu/token.txt", "sudo mv /home/ubuntu/ami_user_data.sh /var/lib/cloud/scripts/per-instance/"]
  }
*/
}
