name: Terraform GitHub Actions
on:
   push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: AWS CLI
        run: |
          aws --version
          aws s3api create-bucket --bucket cloudgeeks-backend1 --region us-east-1
      - name: Terraform Install
        uses: hashicorp/setup-terraform@v1
      - name: Terraform fmt
        id: fmt
        run: | 
          terraform --version
          terraform fmt
        continue-on-error: true
        working-directory: ./demo-1         
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ./demo-1
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color  
        working-directory: ./demo-1     
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true
        working-directory: ./demo-1 
      - name: Terraform Apply
        id: Apply
        run: terraform apply -auto-approve
        continue-on-error: true
        working-directory: ./demo-1   
        
#       - name: terraform destroy
#         uses: dflook/terraform-destroy-workspace@v1
#         with:
#           path: terraform
#           workspace: ${{ github.head_ref }}   
      
#       - name: actionshub-chef-install
#         uses: actionshub/chef-install@main
        
#       - name: Kitchen-Terraform Github Action
#         # You may pin to the exact commit or the version.
#         # uses: osinfra-io/github-kitchen-terraform-action@cf7b74b49d7d88560962e6b8411cbba40c27fc4c
#         uses: osinfra-io/github-kitchen-terraform-action@v1.0.1
#         with:
#     # The command to run for example: help
#         kitchen-command: kitchen create tomcat  
     
    
          

